# Data Prep for Time to Injury Forecasting DeepHit Model

This script replicates this paper https://arxiv.org/html/2601.19479v1 that builds a time-to-injury forecasting model based on the DeebHit model and uses SoccerMon data

In [ ]:
# In your Jupyter Notebook Cell:
from metrics_pipeline import PlayerMetricsPipeline

# 1. Your exact, verified file paths
file_mapping = {
    'data/subjective/training-load/atl.csv': 'ATL',
    'data/subjective/training-load/weekly_load.csv': 'Weekly load',
    'data/subjective/training-load/monotony.csv': 'Monotony',
    'data/subjective/training-load/strain.csv': 'Strain',
    'data/subjective/training-load/acwr.csv': 'ACWR',
    'data/subjective/training-load/ctl28.csv': 'CTL28',
    'data/subjective/training-load/ctl42.csv': 'CTL42',
    'data/subjective/wellness/fatigue.csv': 'Fatigue',
    'data/subjective/wellness/mood.csv': 'Mood',
    'data/subjective/wellness/readiness.csv': 'Readiness',
    'data/subjective/wellness/sleep_duration.csv': 'Sleep duration',
    'data/subjective/wellness/soreness.csv': 'Soreness',
    'data/subjective/wellness/stress.csv': 'Stress'
}

# 3. Instantiate WITH the mapping dictionary explicitly
pipeline = PlayerMetricsPipeline(mapping=file_mapping)
final_df = pipeline.run()

# Display the first few rows
final_df.head()

🚀 Starting pipeline execution...

  ✅ Processed ATL: Generated 36550 rows.
  ✅ Processed Weekly load: Generated 36550 rows.
  ✅ Processed Monotony: Generated 36550 rows.
  ✅ Processed Strain: Generated 36550 rows.
  ✅ Processed ACWR: Generated 36550 rows.
  ✅ Processed CTL28: Generated 36550 rows.
  ✅ Processed CTL42: Generated 36550 rows.
  ✅ Processed Fatigue: Generated 36550 rows.
  ✅ Processed Mood: Generated 36550 rows.
  ✅ Processed Readiness: Generated 36550 rows.
  ✅ Processed Sleep duration: Generated 36550 rows.
  ✅ Processed Soreness: Generated 36550 rows.
  ✅ Processed Stress: Generated 36550 rows.

⏳ Formatting final schema. Total rows merged: 36550...
🎉 Pipeline complete! Final dataset shape: (36550, 15)

,player_name,date,ATL,Weekly load,Monotony,Strain,ACWR,CTL28,CTL42,Fatigue,Mood,Readiness,Sleep duration,Soreness,Stress
0,TeamA-0362cdd5-7a63-480a-a46a-62a99fb1692f,2020-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,TeamA-0362cdd5-7a63-480a-a46a-62a99fb1692f,2020-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,TeamA-0362cdd5-7a63-480a-a46a-62a99fb1692f,2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,TeamA-0362cdd5-7a63-480a-a46a-62a99fb1692f,2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,TeamA-0362cdd5-7a63-480a-a46a-62a99fb1692f,2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 1. Your exact, verified file paths
file_mapping = {
    'data/subjective/training-load/atl.csv': 'ATL',
    'data/subjective/training-load/weekly_load.csv': 'Weekly load',
    'data/subjective/training-load/monotony.csv': 'Monotony',
    'data/subjective/training-load/strain.csv': 'Strain',
    'data/subjective/training-load/acwr.csv': 'ACWR',
    'data/subjective/training-load/ctl28.csv': 'CTL28',
    'data/subjective/training-load/ctl42.csv': 'CTL42',
    'data/subjective/wellness/fatigue.csv': 'Fatigue',
    'data/subjective/wellness/mood.csv': 'Mood',
    'data/subjective/wellness/readiness.csv': 'Readiness',
    'data/subjective/wellness/sleep_duration.csv': 'Sleep duration',
    'data/subjective/wellness/soreness.csv': 'Soreness',
    'data/subjective/wellness/stress.csv': 'Stress'
}

# 3. Instantiate WITH the mapping dictionary explicitly
pipeline = PlayerMetricsPipeline(mapping=file_mapping)
final_df = pipeline.run()

# Display the first few rows
final_df.head()

🚀 Starting pipeline execution...

  ✅ Processed ATL: Generated 36550 rows.
  ✅ Processed Weekly load: Generated 36550 rows.
  ✅ Processed Monotony: Generated 36550 rows.
  ✅ Processed Strain: Generated 36550 rows.
  ✅ Processed ACWR: Generated 36550 rows.
  ✅ Processed CTL28: Generated 36550 rows.
  ✅ Processed CTL42: Generated 36550 rows.
  ✅ Processed Fatigue: Generated 36550 rows.
  ✅ Processed Mood: Generated 36550 rows.
  ✅ Processed Readiness: Generated 36550 rows.
  ✅ Processed Sleep duration: Generated 36550 rows.
  ✅ Processed Soreness: Generated 36550 rows.
  ✅ Processed Stress: Generated 36550 rows.

⏳ Formatting final schema. Total rows merged: 36550...
🎉 Pipeline complete! Final dataset shape: (36550, 15)

,player_name,date,ATL,Weekly load,Monotony,Strain,ACWR,CTL28,CTL42,Fatigue,Mood,Readiness,Sleep duration,Soreness,Stress
0,TeamA-0362cdd5-7a63-480a-a46a-62a99fb1692f,2020-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,TeamA-0362cdd5-7a63-480a-a46a-62a99fb1692f,2020-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,TeamA-0362cdd5-7a63-480a-a46a-62a99fb1692f,2020-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,TeamA-0362cdd5-7a63-480a-a46a-62a99fb1692f,2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,TeamA-0362cdd5-7a63-480a-a46a-62a99fb1692f,2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN